import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { basename, join, relative, sep } from 'node:path'
import { isBriefName } from './curate'
import { parseDoc } from './frontmatter'
import { walkMarkdown } from './scan'

interface NoteEntry {
  name: string
  stale: boolean
}

/** Rebuild _index/Home.md and per-project MOCs from the vault tree. Idempotent — full regenerate. */
export function rebuildIndexes(vaultPath: string): void {
  const byProject = new Map<string, Map<string, NoteEntry[]>>()
  const briefsByProject = new Map<string, string[]>()
  const projectsDir = join(vaultPath, 'projects')

  if (existsSync(projectsDir)) {
    for (const file of walkMarkdown(projectsDir)) {
      const parts = relative(projectsDir, file).split(sep)
      const project = parts[0] as string
      const name = basename(file, '.md')

      // curate briefs live at the project root and get their own MOC section
      if (isBriefName(name)) {
        const briefs = briefsByProject.get(project) ?? []
        briefs.push(name)
        briefsByProject.set(project, briefs)
        continue
      }
      if (parts.length < 3) continue

      let stale = false
      try {
        const status = parseDoc(readFileSync(file, 'utf8')).meta.status
        stale = status === 'stale' || status === 'superseded'
      } catch {
        // unreadable frontmatter — list it plain
      }

      const topic = parts[1] as string
      const topics = byProject.get(project) ?? new Map<string, NoteEntry[]>()
      byProject.set(project, topics)
      const files = topics.get(topic) ?? []
      files.push({ name, stale })
      topics.set(topic, files)
    }
  }

  const indexDir = join(vaultPath, '_index')
  mkdirSync(indexDir, { recursive: true })

  const home: string[] = ['# Home', '', '_Auto-generated by loredex — do not edit by hand._', '']
  if (existsSync(join(vaultPath, 'Start Here - Product.md'))) {
    home.push('**[[Start Here - Product]]** — the cross-project product view', '')
  }
  const allProjects = new Set([...byProject.keys(), ...briefsByProject.keys()])
  for (const project of [...allProjects].sort((a, b) => a.localeCompare(b))) {
    const topics = byProject.get(project) ?? new Map<string, NoteEntry[]>()
    const count = [...topics.values()].reduce((total, files) => total + files.length, 0)
    home.push(`- [[${project}]] — ${count} notes`)

    const moc: string[] = [
      `# ${project}`,
      '',
      '_Auto-generated by loredex — do not edit by hand._',
      '',
    ]
    const briefs = briefsByProject.get(project) ?? []
    if (briefs.length > 0) {
      moc.push('## Start here', '')
      // main brief (shortest name) first, then scoped briefs newest-name first
      for (const name of [...briefs].sort((a, b) => a.length - b.length || b.localeCompare(a))) {
        moc.push(`- [[${name}]]`)
      }
      moc.push('')
    }
    // most recently active topic first — note names start with YYYY-MM-DD, so the
    // lexicographic max of a topic's names is its latest note
    const latest = (files: NoteEntry[]) =>
      files.reduce((max, entry) => (entry.name > max ? entry.name : max), '')
    const byActivity = [...topics].sort(
      (a, b) => latest(b[1]).localeCompare(latest(a[1])) || a[0].localeCompare(b[0]),
    )
    for (const [topic, files] of byActivity) {
      const date = latest(files).match(/^\d{4}-\d{2}-\d{2}/)?.[0]
      moc.push(`## ${topic}${date ? ` — ${date}` : ''}`, '')
      for (const entry of [...files].sort((a, b) => b.name.localeCompare(a.name))) {
        moc.push(`- [[${entry.name}]]${entry.stale ? ' _(stale)_' : ''}`)
      }
      moc.push('')
    }
    writeFileSync(join(indexDir, `${project}.md`), `${moc.join('\n').trimEnd()}\n`)
  }

  const researchDir = join(vaultPath, 'research')
  if (existsSync(researchDir)) {
    const loose = walkMarkdown(researchDir)
    if (loose.length > 0) {
      home.push('', '## Research', '')
      for (const file of loose) {
        home.push(`- [[${basename(file, '.md')}]]`)
      }
    }
  }

  writeFileSync(join(indexDir, 'Home.md'), `${home.join('\n').trimEnd()}\n`)
}
