import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { type ClientInfo, scanFleet, type UnitInfo } from './agent-ops'
import { writeDashboardBase } from './bases'
import { groupProjects, loadProducts } from './products'
import { dataFileSummary } from './tables'

/**
 * Index generation for agent-ops dexes: Home.md groups Manager → Client, each
 * client gets a MOC listing pipelines (with ordered stages), agents, knowledge
 * tables, workflows, and pending inbox. Same contract as the research indexer:
 * full regenerate, idempotent, called via rebuildIndexes' internal dex-type branch
 * so hosts that pass only a vault path get this for free.
 */
export function rebuildAgentOpsIndexes(vaultPath: string): void {
  const fleet = scanFleet(vaultPath)
  const bySlug = new Map(fleet.map((c) => [c.slug, c]))
  const indexDir = join(vaultPath, '_index')
  mkdirSync(indexDir, { recursive: true })
  writeDashboardBase(indexDir)

  const home: string[] = ['# Home', '', '_Auto-generated by loredex — do not edit by hand._', '']
  const groups = groupProjects(
    loadProducts(vaultPath),
    fleet.map((c) => c.slug),
  )
  const grouped = groups.length > 1 || (groups[0] && groups[0].product !== null)
  for (const group of groups) {
    if (grouped) home.push(`## ${group.product ?? 'Unassigned'}`, '')
    for (const slug of group.projects) {
      const info = bySlug.get(slug)
      if (!info) continue
      emitClientMoc(vaultPath, indexDir, info)
      home.push(`- [[${slug}]] — ${clientSummary(info)}`)
    }
    if (grouped) home.push('')
  }
  if (fleet.length === 0) home.push('_No clients yet — `loredex new client <name>`._')

  writeFileSync(join(indexDir, 'Home.md'), `${home.join('\n').trimEnd()}\n`)
}

function clientSummary(info: ClientInfo): string {
  const bits = [
    `${info.pipelines.length} pipeline${info.pipelines.length === 1 ? '' : 's'}`,
    `${info.agents.length} agent${info.agents.length === 1 ? '' : 's'}`,
  ]
  if (info.inboxCount > 0) bits.push(`⚠ ${info.inboxCount} in inbox`)
  const tags = info.tags.map((t) => `#${t}`).join(' ')
  return `${bits.join(' · ')}${tags ? ` ${tags}` : ''}`
}

function emitUnit(moc: string[], unit: UnitInfo): void {
  moc.push(`### ${unit.name}`, '')
  moc.push(`- [[${unit.dir}/_persona|persona]] · [[${unit.dir}/_instructions|instructions]]`)
  if (unit.kind === 'pipeline') {
    for (const stage of unit.stages) {
      moc.push(`- ${stage.nn} — [[${unit.dir}/stages/${stage.dir}/_instructions|${stage.slug}]]`)
    }
    if (unit.stages.length === 0) moc.push('- _no stages yet_')
  }
  moc.push('')
}

/** `orders.csv — 4 columns · 120 rows (order_id, patient, …)` — structural line, contents stay raw. */
function tableLine(vaultPath: string, info: ClientInfo, name: string): string {
  const summary = dataFileSummary(join(vaultPath, info.dir, 'knowledge_tables', name))
  if (!summary || summary.kind !== 'csv' || summary.keys.length === 0) return name
  const headers = summary.keys.slice(0, 6).join(', ')
  const more = summary.keys.length > 6 ? ', …' : ''
  return `${name} — ${summary.keys.length} columns · ${summary.rowCount ?? 0} rows (${headers}${more})`
}

function emitClientMoc(vaultPath: string, indexDir: string, info: ClientInfo): void {
  const moc: string[] = [
    `# ${info.slug}`,
    '',
    '_Auto-generated by loredex — do not edit by hand._',
    '',
  ]
  const meta: string[] = []
  if (info.manager) meta.push(`manager: **${info.manager}**`)
  if (info.tags.length > 0) meta.push(info.tags.map((t) => `#${t}`).join(' '))
  if (meta.length > 0) moc.push(meta.join(' · '), '')
  if (info.inboxCount > 0) {
    moc.push(
      `> ⚠ **${info.inboxCount} inbox item(s) pending** — consume into their proper home.`,
      '',
    )
  }
  if (info.pipelines.length > 0) {
    moc.push('## Pipelines', '')
    for (const unit of info.pipelines) emitUnit(moc, unit)
  }
  if (info.agents.length > 0) {
    moc.push('## Agents', '')
    for (const unit of info.agents) emitUnit(moc, unit)
  }
  if (info.knowledgeTables.length > 0) {
    moc.push('## Knowledge tables', '')
    for (const name of info.knowledgeTables) moc.push(`- ${tableLine(vaultPath, info, name)}`)
    moc.push('')
  }
  if (info.workflows.length > 0) {
    moc.push('## Automation workflows', '')
    for (const name of info.workflows) moc.push(`- ${name}`)
    moc.push('')
  }
  writeFileSync(join(indexDir, `${info.slug}.md`), `${moc.join('\n').trimEnd()}\n`)
}
