import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { basename, join, relative, sep } from 'node:path'
import { walkMarkdown } from './scan'

/** Rebuild _index/Home.md and per-project MOCs from the vault tree. Idempotent — full regenerate. */
export function rebuildIndexes(vaultPath: string): void {
  const byProject = new Map<string, Map<string, string[]>>()
  const projectsDir = join(vaultPath, 'projects')
  if (existsSync(projectsDir)) {
    for (const file of walkMarkdown(projectsDir)) {
      const parts = relative(projectsDir, file).split(sep)
      if (parts.length < 3) continue
      const project = parts[0] as string
      const topic = parts[1] as string
      const name = basename(file, '.md')
      const topics = byProject.get(project) ?? new Map<string, string[]>()
      byProject.set(project, topics)
      const files = topics.get(topic) ?? []
      files.push(name)
      topics.set(topic, files)
    }
  }

  const indexDir = join(vaultPath, '_index')
  mkdirSync(indexDir, { recursive: true })

  const home: string[] = ['# Home', '', '_Auto-generated by loredex — do not edit by hand._', '']
  for (const [project, topics] of [...byProject].sort((a, b) => a[0].localeCompare(b[0]))) {
    const count = [...topics.values()].reduce((total, files) => total + files.length, 0)
    home.push(`- [[${project}]] — ${count} notes`)

    const moc: string[] = [
      `# ${project}`,
      '',
      '_Auto-generated by loredex — do not edit by hand._',
      '',
    ]
    for (const [topic, files] of [...topics].sort((a, b) => a[0].localeCompare(b[0]))) {
      moc.push(`## ${topic}`, '')
      for (const name of [...files].sort().reverse()) {
        moc.push(`- [[${name}]]`)
      }
      moc.push('')
    }
    writeFileSync(join(indexDir, `${project}.md`), `${moc.join('\n').trimEnd()}\n`)
  }

  const researchDir = join(vaultPath, 'research')
  if (existsSync(researchDir)) {
    const loose = walkMarkdown(researchDir)
    if (loose.length > 0) {
      home.push('', '## Research', '')
      for (const file of loose) {
        home.push(`- [[${basename(file, '.md')}]]`)
      }
    }
  }

  writeFileSync(join(indexDir, 'Home.md'), `${home.join('\n').trimEnd()}\n`)
}
